class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for communities generated by controller generator
  resources :communities, only: [:index]
  # End routes for communities

  # Routes for video_resources generated by controller generator
  resources :video_resources, only: [:index, :show]
  # End routes for video_resources

  # Routes for resources (website resources)
  resources :resources, only: [:index, :show]
  # End routes for resources

  # Routes for skills generated by controller generator
  resources :skills, only: [:index, :show] do
    member do
      post :purchase
    end
  end
  # End routes for skills

  resources :payments, only: [] do
    member do
      get :pay
      post :pay
      get :success
      get :failure
    end
  end
  post '/webhooks/stripe', to: 'payments#webhook'
  # Authentication routes（微信登录专用，邮箱/密码/设备相关已移除）
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out

  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"

  # Profile setup (post-wechat-login onboarding)
  get  'profile/setup', to: 'profile_setup#show',   as: :profile_setup
  post 'profile/setup', to: 'profile_setup#update'

  # SMS verification codes
  resources :verification_codes, only: [:create]

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles'

  # Law firm autocomplete
  get 'law_firms/autocomplete', to: 'law_firms#autocomplete'

  # Authentication routes generated end

  # WeChat MP login routes
  namespace :wechat do
    get  'mp', to: 'mp#verify'
    post 'mp', to: 'mp#callback'
    get  'qrcode', to: 'qrcode#show'
    get  'check',  to: 'qrcode#check'

    # WeChat Pay routes
    namespace :pay do
      get  'order',         to: 'orders#new',       as: :order_new
      post 'order',         to: 'orders#create',    as: :order_create
      get  'order/success', to: 'orders#success',   as: :order_success
      get  'status/:out_trade_no', to: 'status#show', as: :status
      post 'notify',        to: 'notify#callback',  as: :notify
    end
  end

  # Development-only mock login
  if Rails.env.development?
    namespace :dev do
      get  'mock_login', to: 'mock_login#index'
      post 'mock_login', to: 'mock_login#create'
    end
  end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :resources
    resources :skills
    resources :video_resources
    resources :categories
    resources :skill_categories
    resources :payments, only: [:index, :show]
    resources :users, only: [:index, :show]
    resources :law_firms
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage') &&
      !request.path.start_with?('/.well-known/') &&
      request.path != '/favicon.ico'
    }
end
