class AdminConstraint
  def matches?(request)
    return false unless request.session[:current_admin_id].present?

    admin = Administrator.find_by(id: request.session[:current_admin_id])
    admin.present?
  end
end

Rails.application.routes.draw do
  # Routes for communities generated by controller generator
  resources :communities, only: [:index]
  # End routes for communities

  # 线下课程报名
  resources :offline_classes, only: [:index] do
    member do
      post :enroll
      delete :unenroll
    end
  end

  # Routes for video_resources generated by controller generator
  resources :video_resources, only: [:index, :show]
  # End routes for video_resources

  # Routes for resources (website resources)
  resources :resources, only: [:index, :show]
  # End routes for resources

  # Routes for skills
  resources :skills, only: [:index, :show] do
    member do
      post :purchase
    end
  end

  resources :payments, only: [] do
    member do
      get :pay
      post :pay
      get :success
      get :failure
    end
  end
  post '/webhooks/stripe', to: 'payments#webhook'
  # Authentication routes（微信登录专用，邮箱/密码/设备相关已移除）
  # sign_in_path / sign_up_path 别名 → 微信扫码登录页，保持兼容旧引用
  get  'sign_in',  to: redirect('/wechat/qrcode'), as: :sign_in
  post 'sign_in',  to: 'sessions/registrations#create'
  get  'sign_up',  to: redirect('/wechat/qrcode'), as: :sign_up
  post 'sign_up',  to: 'sessions/registrations#create'
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out

  get  "/auth/failure",              to: "sessions/omniauth#failure"
  get  "/auth/wechat/handoff",       to: "sessions/wechat_handoff#show", as: :auth_wechat_handoff
  get  "/auth/:provider/callback",   to: "sessions/omniauth#create"
  post "/auth/:provider/callback",   to: "sessions/omniauth#create"

  # Profile setup (post-wechat-login onboarding)
  get  'profile/setup', to: 'profile_setup#show',   as: :profile_setup
  post 'profile/setup', to: 'profile_setup#update'

  # API endpoints (exempt from turbo-stream validation)
  namespace :api do
    resources :verification_codes, only: [:create]
    get 'law_firms/autocomplete', to: 'law_firms#autocomplete'
  end

  # Profile routes
  resource :profile, only: [:show, :edit, :update], controller: 'profiles'

  # Authentication routes generated end

  # WeChat MP login routes
  namespace :wechat do
    get  'mp', to: 'mp#verify'
    post 'mp', to: 'mp#callback'

    # Open Platform WxLogin (PC QR code login)
    get  'qrcode', to: 'qrcode#show'
    # Legacy MP check endpoint (kept for backward compatibility)
    get  'check',  to: 'qrcode#check'

    # MP OAuth silent authorization (for JSAPI payment openid)
    scope :mp_oauth do
      get  'authorize', to: 'mp_oauth#authorize', as: :mp_oauth_authorize
      get  'callback',  to: 'mp_oauth#callback',  as: :mp_oauth_callback
    end

    # WeChat Pay routes
    namespace :pay do
      get  'order',         to: 'orders#new',       as: :order_new
      post 'order',         to: 'orders#create',    as: :order_create
      get  'order/success', to: 'orders#success',   as: :order_success
      post 'notify',        to: 'notify#callback',  as: :notify
    end
  end

  # Development-only mock login
  if Rails.env.development?
    namespace :dev do
      get  'mock_login', to: 'mock_login#index'
      post 'mock_login', to: 'mock_login#create'
    end
  end

  # write your business logic routes here

  # API routes
  namespace :api do
    namespace :v1 do
      # API authentication routes
      post 'login', to: 'sessions#login'
      delete 'logout', to: 'sessions#destroy'
      post 'sign_up', to: 'registrations#create'
      resource :profile, only: [:show, :update], controller: 'profiles'
      put 'password', to: 'profiles#update_password'

      get 'health', to: 'health#index'
    end
  end

  root 'home#index'

  # Do not write business logic at admin dashboard
  namespace :admin do
    resources :resources
    resources :skills
    resources :video_resources
    resources :categories
    resources :skill_categories
    resources :delivered_skills do
      member do
        post :move_up
        post :move_down
      end
    end
    resources :payments, only: [:index, :show]
    resources :offline_classes do
      member do
        get :show  # 报名列表
      end
    end
    resources :wechat_orders, only: [:index, :show, :edit, :update]
    resources :users, only: [:index, :show]
    resources :law_firms
    resources :admin_oplogs, only: [:index, :show]
    resources :administrators
    get 'login', to: 'sessions#new', as: :login
    post 'login', to: 'sessions#create'
    delete 'logout', to: 'sessions#destroy', as: :logout
    resource :account, only: [:edit, :update]
    resource :site_settings, only: [:edit, :update]

    # Mount GoodJob dashboard
    mount GoodJob::Engine => 'good_job', :constraints => AdminConstraint.new

    root to: 'dashboard#index'
  end

  mount ActionCable.server => '/cable'

  # Catch-all route for all 404 errors - MUST be last
  match '*path', to: 'application#handle_routing_error', via: :all,
    constraints: lambda { |request|
      !request.path.start_with?('/rails/active_storage') &&
      !request.path.start_with?('/.well-known/') &&
      request.path != '/favicon.ico'
    }
end
